import { Router } from "express";
import { PrismaClient } from "@prisma/client";
import { authenticate } from "../middleware/auth.middleware";

const router = Router();
const prisma = new PrismaClient();

/*
GET all saved career plans for logged-in user
*/
router.get("/", authenticate, async (req, res) => {

  try {

    const userId = (req as any).user.id;

    const plans = await prisma.careerPlan.findMany({
      where: { userId }
    });

    res.json(plans);

  } catch (error) {

    console.error(error);
    res.status(500).json({ message: "Failed to fetch career plans" });

  }

});


/*
SAVE career plan generated by AI
*/
router.post("/save", authenticate, async (req, res) => {

  try {

    const { role, jobDescription, aiPlan } = req.body;

    const userId = (req as any).user.id;

    const plan = await prisma.careerPlan.create({
      data: {
        role,
        jobDescription,
        aiPlan,
        userId
      }
    });

    res.json(plan);

  } catch (error) {

    console.error(error);
    res.status(500).json({ message: "Failed to save career plan" });

  }

});

export default router;